before:
  hooks:
    # create version-info.go file
    - make version

builds:
  - goos:
      - freebsd
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - "386"
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: "386"
changelog:
  skip: true
